apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sopes1-ingress
  namespace: sopes1
  labels:
    name: sopes1-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: 34.19.89.99.nip.io
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: api-rust
                port:
                  number: 8081
            path: /input
