// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/service.proto

package tweet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tweet_SendTweet_FullMethodName = "/tweet.Tweet/SendTweet"
)

// TweetClient is the client API for Tweet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetClient interface {
	SendTweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error)
}

type tweetClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetClient(cc grpc.ClientConnInterface) TweetClient {
	return &tweetClient{cc}
}

func (c *tweetClient) SendTweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*TweetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TweetResponse)
	err := c.cc.Invoke(ctx, Tweet_SendTweet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetServer is the server API for Tweet service.
// All implementations must embed UnimplementedTweetServer
// for forward compatibility.
type TweetServer interface {
	SendTweet(context.Context, *TweetRequest) (*TweetResponse, error)
	mustEmbedUnimplementedTweetServer()
}

// UnimplementedTweetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTweetServer struct{}

func (UnimplementedTweetServer) SendTweet(context.Context, *TweetRequest) (*TweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTweet not implemented")
}
func (UnimplementedTweetServer) mustEmbedUnimplementedTweetServer() {}
func (UnimplementedTweetServer) testEmbeddedByValue()               {}

// UnsafeTweetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetServer will
// result in compilation errors.
type UnsafeTweetServer interface {
	mustEmbedUnimplementedTweetServer()
}

func RegisterTweetServer(s grpc.ServiceRegistrar, srv TweetServer) {
	// If the following call pancis, it indicates UnimplementedTweetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tweet_ServiceDesc, srv)
}

func _Tweet_SendTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServer).SendTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tweet_SendTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServer).SendTweet(ctx, req.(*TweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tweet_ServiceDesc is the grpc.ServiceDesc for Tweet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tweet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tweet.Tweet",
	HandlerType: (*TweetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTweet",
			Handler:    _Tweet_SendTweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
